name: Build & Test

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        description: 'Branch or tag ref to check out'
        type: string
        required: false
        default: ''
      artifact_name:
        description: 'Name of the artifact to upload'
        type: string
        required: false
        default: 'npm-package'

permissions:
  contents: read

jobs:
  build_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.ref || '' }}
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: 'package.json'
      - run: npm ci
      - name: test
        env:
          CI: true
          COVERAGE: true
          FLAKEY: false
        # Not using `npm test` since it rebuilds source which npm ci has already done
        run: npm run lint && npm run test:unit
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@643bc377ffa44ace6394b2b5d0d3950076de9f63 # v2.3.0
        timeout-minutes: 2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          fail-on-error: false
      - name: Package
        # Use --ignore-scripts here to avoid re-building again before pack
        run: |
          npm pack --ignore-scripts
          mv preact-*.tgz preact.tgz
      - name: Upload npm package
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ${{ inputs.artifact_name || 'npm-package' }}
          path: preact.tgz
